# Generated by Django 4.2.4 on 2024-01-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recorrido',
        ),
    ]
