# Generated by Django 4.2.4 on 2024-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProyectoHistoryArApp', '0002_delete_recorrido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='puntos_interes')),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.CharField(max_length=100)),
                ('puntoInteres', models.ManyToManyField(to='ProyectoHistoryArApp.puntosinteres')),
            ],
        ),
    ]
