# Generated by Django 4.2.4 on 2024-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0007_remove_recorridos_puntointeres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('recorridoFavorito', models.CharField(max_length=255)),
                ('ultimosRecorridos', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='puntosinteres',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puntosinteres',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puntosinteres',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='puntosinteres',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='recorridos',
            name='puntoInteres',
        ),
        migrations.AddField(
            model_name='recorridos',
            name='puntoInteres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
