# Generated by Django 4.2.4 on 2024-02-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='imagen',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
