# Generated by Django 4.2.4 on 2024-02-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0002_remove_recorrido_imagen_recorrido_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorrido',
            old_name='puntos',
            new_name='puntoInteres',
        ),
    ]
