# Generated by Django 4.2.4 on 2024-03-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0003_rename_puntos_recorrido_puntointeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
