# Generated by Django 4.2.4 on 2024-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
