# Generated by Django 4.2.4 on 2024-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_alter_transaccion_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='mp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
