# Generated by Django 4.2.4 on 2024-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_alter_transaccion_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTransaccion', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
