# Generated by Django 4.2.4 on 2024-03-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_transaccion_mp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado_pago',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
