# Generated by Django 4.2.4 on 2024-03-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0005_remove_transaccion_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='usuario_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
