# Generated by Django 4.2.4 on 2024-03-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0006_transaccion_usuario_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario_str',
        ),
    ]
