# Generated by Django 4.2.4 on 2024-03-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0007_remove_transaccion_usuario_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
