# Generated by Django 4.2.4 on 2024-02-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pInteres', '0002_alter_puntointeres_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeres',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
