# Generated by Django 4.2.4 on 2024-02-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0004_alter_recorridos_puntointeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntosinteres',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='puntos_interes'),
        ),
    ]
