# Generated by Django 4.2.4 on 2024-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0005_alter_puntosinteres_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorridos',
            name='puntoInteres',
        ),
        migrations.AddField(
            model_name='recorridos',
            name='puntoInteres',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
