# Generated by Django 4.2.4 on 2024-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0006_remove_recorridos_puntointeres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorridos',
            name='puntoInteres',
        ),
        migrations.AddField(
            model_name='recorridos',
            name='puntoInteres',
            field=models.ManyToManyField(to='ProyectoHistoryArApp.puntosinteres'),
        ),
    ]
