# Generated by Django 4.2.4 on 2024-02-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0008_usuario_alter_puntosinteres_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('recorrido', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.TextField(blank=True, max_length=255, null=True)),
                ('puntuacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
