# Generated by Django 4.2.4 on 2024-03-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0009_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='recorridoFavorito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimosRecorridos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
