# Generated by Django 4.2.4 on 2024-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoHistoryArApp', '0010_alter_usuario_recorridofavorito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recorridos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
