# Generated by Django 4.2.4 on 2024-01-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.AddField(
            model_name='usuario',
            name='recorridoFavorito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorrido.recorrido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimosRecorridos',
            field=models.ManyToManyField(blank=True, related_name='ultimosRecorridos', to='recorrido.recorrido'),
        ),
    ]
