# Generated by Django 4.2.4 on 2024-03-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0004_alter_recorrido_descripcion'),
        ('usuario', '0003_alter_usuario_recorridofavorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultimosRecorridos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimosRecorridos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimosRecorridos', to='recorrido.recorrido'),
        ),
    ]
