# Generated by Django 4.2.4 on 2024-02-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorrido', '0003_rename_puntos_recorrido_puntointeres'),
        ('usuario', '0002_remove_usuario_apellido_usuario_recorridofavorito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('puntuacion', models.IntegerField()),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorrido.recorrido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
